### ISSUE TITLE
Performance improvement for totalLoad

### ISSUE THREAD

**Issue by SkyLined** [KyleRoss/windows-cpu#3]
I found totalLoad was spaning cmd.exe processes, which were spawning wmic.exe processes, all of which were consuming CPU and memory. To make this more efficient, I've removed the need for the cmd.exe process by replacing exec with execFile:

At the top of windows-cpu.js, add the following:
```javascript
        execFile = require('child_process').execFile,
        path     = require('path'),
```
Then, replace the totalLoad function with this:
```javascript
    exports.totalLoad = function totalLoad(cb) {
        if (!isFunction(cb)) cb = emptyFn;
        if (!checkPlatform(cb)) return;
        wmic_path = path.join(process.env.SystemRoot, "System32", "wbem", "wmic.exe");
        execFile(wmic_path, ["cpu", "get", "loadpercentage"],
          function(error, res, stderr) {
            if (error !== null || stderr) {
                return cb(error || stderr);
            }
            var cpus = res.match(/\d+/g).filter(function(x){return +x;});
            cb(null, cpus);
          }
        );
    };
```
I think you can improve the other functions in a similar manner, but since I don't use them, I haven't looked at that.

I hope this helps. I don't use git, so I can't follow your referred contribution process.

**Comment by KyleRoss** [comment]
Thanks for letting me know. I went ahead and pushed in the changes to a couple of the functions to help the performance. As for the few others that still use `cmd`, I will keep it that way as it is faster to have it do some of the filtering for me instead of doing it within JavaScript. If someone has a better method, please feel free to submit a pull request.

All tests are passing and version `0.1.3` has been published to NPM.
